### PR TITLE
Fix/displaycurrentkey

### PR DESCRIPTION
**Pull request by willoucom**
Hello,

I have translated the addon in French.

During the translation i found the scheduler is not working anymore, so I removed it and move frames a little bit for more readability.

image

Let me know if this is OK.

### CODE REVIEW

**Comment by Dairyman** [comment]
Updated schedule for 9.1:
```Lua
local affixSchedule = {
	[1]  = {[1]=11, [2]=3,  [3]=10}, -- 1 Bursting Volcanic Fortified
	[2]  = {[1]=7,  [2]=124,[3]=9},  -- 2 Bolstering Storming Tyrannical
	[3]  = {[1]=123,[2]=12, [3]=10}, -- 3 Spiteful Grievous Fortified
	[4]  = {[1]=122,[2]=4,  [3]=9},  -- 4 Inspiring Necrotic Tyrannical
	[5]  = {[1]=8,  [2]=14, [3]=10}, -- 5 Sanguine Quaking Fortified
	[6]  = {[1]=6,  [2]=13, [3]=9},  -- 6 Raging Explosive Tyrannical
	[7]  = {[1]=123,[2]=3,  [3]=10}, -- 7 Spiteful Volcanic Fortified
	[8]  = {[1]=7,  [2]=4,  [3]=9},  -- 8 Bolstering Necrotic Tyrannical
	[9]  = {[1]=122,[2]=124,[3]=10}, -- 9 Inspiring Storming Fortified
	[10] = {[1]=11, [2]=13, [3]=9},  --10 Bursting Explosive Tyrannical
	[11] = {[1]=8,  [2]=12, [3]=10}, --11 Sanguine Grievous Fortified
	[12] = {[1]=6,  [2]=14, [3]=9},  --12 Raging Quaking Tyrannical
}
```

**Comment by Ermad** [comment]
Sorry for delay but released version with the French locale added.

**Comment by Ermad** [comment]
What is exactly wrong with the Schedule? I am not playing atm so can't test in game.

@Dairyman isn't that the same schedule that is currently in the addon?

**Comment by Dairyman** [comment]
..right, updated with correct schedule.

**Comment by willoucom** [comment]
After weeks of testing, my modifications to the UI is not recommended anymore.
Instead, can you change the width of the keystone name in Schedule.lua:289 
| keystoneText:SetWidth(320)

In some languages, french for example, keyname can be very long (eg: Salles de l'expiation (14) or Brumes de tirna scithe (14) ) and will be cropped without the modification of the width

**Comment by madar2252** [comment]
> 
> 
> What is exactly wrong with the Schedule? I am not playing atm so can't test in game.
> 
> @Dairyman isn't that the same schedule that is currently in the addon?

The schedule changed with 9.1
With the actual data in the addon you get the following screen:



Both the modification by willoucoum with the setwidth needed to don't overlap the own keytext, and the new schedule by Dairyman is needed to show the schedule.

After these 2 modifications:



(still not the best tho, as the new Blizzard vault icon having a shadow effect over the addon's key text. Would be better to move the info somewhere else, but until then this is a quick fix)

**Comment by Ermad** [comment]
Released version with update schedule, and width change. Feel free to open new issue/pull for anymore changes/additions.

**Pull request closed without merging**
